#!/usr/bin/php;
<?php
if(php_sapi_name() !== 'cli'){
	exit();
}
//- enter correct path
require __DIR__.'/../vendor/autoload.php';

use Microcli\Microcli;

$app = new Microcli();

//- set symbol for prefix
$app->prefix('>');

$app->line()->write('All colors')->line();

foreach($app->getColors() as $name => $code){
	//- set symbol for line
	$app->line('~', 1);

	$name_color = str_replace('_alt', ' Background', ucwords($name));

	$app->color($name)->write($name_color.' ('.$code.'): $app->color(\''.$name.'\')->write(\'Test color\')');
}

